### ISSUE TITLE
Justification for the choices.

### ISSUE THREAD

**Issue by biraj-dahal** [biraj-dahal/Team-11-Senior-Project#2]
This Issue will cover the overview of Amazon Pitch, which is held on September 12, 2024, and solid points on why do we have it as a preference.

**Comment by biraj-dahal** [comment]
Option 1: Autonomy/Autonomous Navigation
Option 2: Remote Control Robotic Arm Manipulation


Link from Amanda: https://docs.google.com/document/u/0/d/1BzJnWW6tsbjr2Ad29JjYLKIRaqYA-zL4MpjTjkJdK3Q/mobilebasic

Link from Dr. Keeling: https://docs.google.com/document/d/1JEmhv3wLwfqq-nnZCcWOH0g4J_FaD-YmR3vysihBAhE/edit

**Comment by biraj-dahal** [comment]
Please comment on this issue with respective justifications.

Amazon Robotics - Biraj Dahal
AWS Connect - Hrishav Sapkota
AWS Small Businesses - Amir Ince

**Comment by hri-sap** [comment]
**Amazon Connect:**

Our senior project team is eager to be sponsored by Amazon Connect due to the project's direct relevance to a key customer need: enhancing Amazon Connect's value in the contact center market. We want to be tackling innovative challenges like screen recording and PII detection, which have immediate real-world applications for improving agent training, quality assurance, and compliance. The full-stack implementation allows us to showcase our technical skills across various AWS services, aligning with Amazon Connect's growth goals in the competitive contact center industry. This collaboration offers us invaluable learning opportunities and potential career prospects with a tech giant. Additionally, by releasing our project as open-source, we're contributing to the broader developer community. Thus, this would be a great match for our team and Amazon.

**Comment by amirince** [comment]
**Amazon Small Businesses:**

As a group of international students, we are particularly drawn to the Amazon Small Businesses project because the issues highlighted resonate deeply with the challenges we’ve encountered in our own experiences. Navigating different systems and adapting to new environments are realities we face daily, and we see the potential to address similar global complexities using AI/ML and our computer science skills. This project offers us the opportunity to leverage our technical expertise, combined with our diverse perspectives, to create real-world impact. We’re excited about applying cutting-edge technology to solve problems that transcend borders, making meaningful and lasting contributions.

**Comment by biraj-dahal** [comment]
**Amazon Robotics:**

We are excited for the possibility to be sponsored by Amazon Robotics, a field that perfectly aligns with both our technical expertise and our passion for innovation. All of us are taking an advanced robotics autonomous navigation course in collaboration with the University of Michigan, which gives us a deep understanding of the latest developments in the field. We have already brainstormed innovative ideas in both autonomous navigation and robotic arms, with one of our team members having hands-on experience using ROS with Dense Tact Sensors for delicate object handling. This expertise positions us uniquely to contribute valuable solutions to Amazon Robotics’ ongoing projects. We are a group of highly motivated seniors, eager not only to build cutting-edge robotic systems but also to go beyond the practical implementation by conducting research on the utility of these systems. Publishing a research paper based on our work would be a huge step toward advancing our academic careers, especially for those of us planning to attend graduate school.

**Comment by biraj-dahal** [comment]
Review: Suprabhat

**Comment by suprabhatrijal** [comment]
Everything looks great! Good artifact for posteriority!
